# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: mattgb/pawgistics_build_env:0.0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-build-deps-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-build-deps-

      - run:
          name: Install dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-build-deps-{{ checksum "package.json" }}

      - run:
          name: Build project
          command: |
            yarn prod:build

      - restore_cache:
          keys:
          - v1-prod-deps-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-prod-deps-

      - run:
          name: Prune bundle deps
          command: |
            yarn install --prod

      - save_cache:
          paths:
            - node_modules
          key: v1-prod-deps-{{ checksum "package.json" }}

      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            eb deploy --process Staging
            fi
